#!/bin/bash

echo "🔧 Ejecutando Spotless..."

cd backend || exit 1

./gradlew spotlessApply --no-daemon

if [ $? -ne 0 ]; then
	echo "❌ Spotless falló. Commit cancelado."
	exit 1
fi

cd ..

git add backend

echo "✅ Código formateado correctamente."
