spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/gestion_escolar
    username: postgres
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    time-zone: America/Argentina/Buenos_Aires

server:
  port: 8080
  error:
    include-message: always
