package com.gestion.escuela.gestion_escolar.models.enums;

public enum RolEducativo {
	DIRECCION,
	VICEDIRECCION,
	SECRETARIA,
	ORIENTACION_EDUCACIONAL,
	ORIENTACION_SOCIAL,
	PRECEPTORIA,
	DOCENTE,
	AUXILIAR,
	ENCARGO_DE_MEDIO_DE_APOYO_TECNICO_PROFESIONAL,
	SIN_CARGO,

}
