-- ASIGNACION

CREATE TABLE asignacion
(
    id                    bigint GENERATED BY DEFAULT AS IDENTITY,
    tipo_asignacion       varchar(31) NOT NULL,
    causa                 varchar(255),
    fecha_baja            date,
    fecha_desde           date,
    fecha_hasta           date,
    caracteristica_id     bigint,
    designacion_id        bigint      NOT NULL,
    empleado_educativo_id bigint      NOT NULL,

    CONSTRAINT asignacion_pkey PRIMARY KEY (id),

    CONSTRAINT asignacion_causa_check CHECK (
        causa IS NULL OR
        causa IN
        (
         'RENUNCIA_POR_CAUSAS_PARTICULARES',
         'RENUNCIA_POR_CESE',
         'JUBILACION',
         'FALLECIMIENTO',
         'PASE_DE_SUPLENTE_A_PROVISIONAL',
         'OTRAS'
            )
        )
);

CREATE TABLE asignacion_provisional
(
    id bigint NOT NULL,
    CONSTRAINT asignacion_provisional_pkey PRIMARY KEY (id)
);

CREATE TABLE asignacion_suplente
(
    id bigint NOT NULL,
    CONSTRAINT asignacion_suplente_pkey PRIMARY KEY (id)
);

CREATE TABLE asignacion_titular
(
    id bigint NOT NULL,
    CONSTRAINT asignacion_titular_pkey PRIMARY KEY (id)
);

-- ASISTENCIA

CREATE TABLE asistencia
(
    id                    bigint GENERATED BY DEFAULT AS IDENTITY,
    estado_asistencia     varchar(255) NOT NULL,
    fecha                 date         NOT NULL,
    observacion           varchar(255),
    origen_asistencia     varchar(255) NOT NULL,
    tipo_licencia         varchar(255),
    empleado_educativo_id bigint       NOT NULL,
    escuela_id            bigint       NOT NULL,
    licencia_id           bigint,

    CONSTRAINT asistencia_pkey PRIMARY KEY (id),

    CONSTRAINT asistencia_estado_check
        CHECK (estado_asistencia IN
               ('AUSENTE',
                'PRESENTE')),

    CONSTRAINT asistencia_origen_check
        CHECK (origen_asistencia IN
               ('MANUAL',
                'LICENCIA')),

    CONSTRAINT asistencia_tipo_licencia_check
        CHECK (
            tipo_licencia IS NULL OR
            tipo_licencia IN
            (
             'L_A1',
             'L_A2',
             'L_A22',
             'L_A2211',
             'L_B1',
             'L_B2',
             'L_114C',
             'L_114D',
             'L_114E',
             'L_114F1',
             'L_114F2',
             'L_114F3',
             'L_114F4',
             'L_114G',
             'L_114H1',
             'L_114I',
             'L_114J',
             'L_114K',
             'L_114L',
             'L_114LL11',
             'L_114LL12',
             'L_114LL13',
             'L_114LL14',
             'L_114LL15',
             'L_114LL2',
             'L_114LL3',
             'L_114M',
             'L_114M11',
             'L_114M12',
             'L_114N',
             'L_114N1',
             'L_114O1',
             'L_114O2',
             'L_114O3',
             'L_114O4',
             'L_114O5',
             'L_115A1',
             'L_115A2',
             'L_115B1',
             'L_115B2',
             'L_115B3',
             'L_115B4',
             'L_115C',
             'L_115D1',
             'L_115E1',
             'L_115E2',
             'L_115E3'
                )
            )
);


CREATE TABLE caracteristica_asignacion
(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY,
    tipo_caracteristica varchar(31) NOT NULL,

    CONSTRAINT caracteristica_asignacion_pkey PRIMARY KEY (id)
);


CREATE TABLE curso
(
    id         bigint GENERATED BY DEFAULT AS IDENTITY,
    anio       integer      NOT NULL,
    grado      integer      NOT NULL,
    turno      varchar(255) NOT NULL,
    escuela_id bigint       NOT NULL,

    CONSTRAINT curso_pkey PRIMARY KEY (id),

    CONSTRAINT curso_turno_check CHECK (
        turno IN
        ('MANIANA',
         'TARDE',
         'VESPERTINO')
        ),

    CONSTRAINT uk_curso UNIQUE (escuela_id,
                                anio,
                                grado,
                                turno)
);

-- DESIGNACION

CREATE TABLE designacion
(
    id            bigint GENERATED BY DEFAULT AS IDENTITY,
    cupof         integer      NOT NULL,
    rol_educativo varchar(255) NOT NULL,
    escuela_id    bigint       NOT NULL,

    CONSTRAINT designacion_pkey PRIMARY KEY (id),

    CONSTRAINT designacion_rol_check CHECK (
        rol_educativo IN
        (
         'DIRECCION',
         'VICEDIRECCION',
         'SECRETARIA',
         'BIBLIOTECARIO',
         'ORIENTACION_EDUCACIONAL',
         'ORIENTACION_SOCIAL',
         'PRECEPTORIA',
         'DOCENTE',
         'AUXILIAR',
         'ENCARGO_DE_MEDIO_DE_APOYO_TECNICO_PROFESIONAL'
            )
        ),

    CONSTRAINT uk_designacion UNIQUE (escuela_id,
                                      cupof)
);

CREATE TABLE designacion_administrativa
(
    id bigint NOT NULL,
    CONSTRAINT designacion_administrativa_pkey PRIMARY KEY (id)
);

CREATE TABLE designacion_curso
(
    id          bigint       NOT NULL,
    orientacion varchar(255) NOT NULL,
    curso_id    bigint       NOT NULL,
    materia_id  bigint       NOT NULL,

    CONSTRAINT designacion_curso_pkey PRIMARY KEY (id)
);

-- EMPLEADO EDUCATIVO 

CREATE TABLE empleado_educativo
(
    id                  bigint GENERATED BY DEFAULT AS IDENTITY,
    activo              boolean      NOT NULL,
    apellido            varchar(255) NOT NULL,
    cuil                varchar(255) NOT NULL,
    domicilio           varchar(255),
    email               varchar(255) NOT NULL,
    fecha_de_ingreso    date,
    fecha_de_nacimiento date         NOT NULL,
    nombre              varchar(255) NOT NULL,
    telefono            varchar(255),
    escuela_id          bigint       NOT NULL,

    CONSTRAINT empleado_educativo_pkey PRIMARY KEY (id),

    CONSTRAINT uk_cuil_escuela UNIQUE (cuil,
                                       escuela_id),
    CONSTRAINT uk_email_escuela UNIQUE (email,
                                        escuela_id)
);

-- ESCUELA

CREATE TABLE escuela
(
    id        bigint GENERATED BY DEFAULT AS IDENTITY,
    activa    boolean      NOT NULL,
    direccion varchar(255),
    localidad varchar(255) NOT NULL,
    nombre    varchar(255) NOT NULL,
    telefono  varchar(255),

    CONSTRAINT escuela_pkey PRIMARY KEY (id),
    CONSTRAINT uk_escuela UNIQUE (nombre,
                                  localidad)
);

-- FRANJA HORARIA

CREATE TABLE franja_horaria
(
    id             bigint GENERATED BY DEFAULT AS IDENTITY,
    dia            varchar(255) NOT NULL,
    hora_desde     time         NOT NULL,
    hora_hasta     time         NOT NULL,
    designacion_id bigint       NOT NULL,

    CONSTRAINT franja_horaria_pkey PRIMARY KEY (id),

    CONSTRAINT franja_horaria_dia_check CHECK (
        dia IN
        ('LUNES',
         'MARTES',
         'MIERCOLES',
         'JUEVES',
         'VIERNES')
        )
);

-- LICENCIA

CREATE TABLE licencia
(
    id                   bigint GENERATED BY DEFAULT AS IDENTITY,
    descripcion          varchar(500),
    fecha_desde          date,
    fecha_hasta          date,
    tipo_licencia        varchar(255) NOT NULL,
    empleado_id          bigint       NOT NULL,
    licencia_anterior_id bigint,

    CONSTRAINT licencia_pkey PRIMARY KEY (id),

    CONSTRAINT licencia_tipo_licencia_check
        CHECK (
            tipo_licencia IN
            (
             'L_A1',
             'L_A2',
             'L_A22',
             'L_A2211',
             'L_B1',
             'L_B2',
             'L_114C',
             'L_114D',
             'L_114E',
             'L_114F1',
             'L_114F2',
             'L_114F3',
             'L_114F4',
             'L_114G',
             'L_114H1',
             'L_114I',
             'L_114J',
             'L_114K',
             'L_114L',
             'L_114LL11',
             'L_114LL12',
             'L_114LL13',
             'L_114LL14',
             'L_114LL15',
             'L_114LL2',
             'L_114LL3',
             'L_114M',
             'L_114M11',
             'L_114M12',
             'L_114N',
             'L_114N1',
             'L_114O1',
             'L_114O2',
             'L_114O3',
             'L_114O4',
             'L_114O5',
             'L_115A1',
             'L_115A2',
             'L_115B1',
             'L_115B2',
             'L_115B3',
             'L_115B4',
             'L_115C',
             'L_115D1',
             'L_115E1',
             'L_115E2',
             'L_115E3'
                )
            )
);

CREATE TABLE licencia_designacion
(
    licencia_id    bigint NOT NULL,
    designacion_id bigint NOT NULL,

    CONSTRAINT licencia_designacion_pkey
        PRIMARY KEY (licencia_id,
                     designacion_id)
);

-- MATERIA

CREATE TABLE materia
(
    id               bigint GENERATED BY DEFAULT AS IDENTITY,
    abreviatura      varchar(255) NOT NULL,
    cantidad_modulos integer      NOT NULL,
    nombre           varchar(255) NOT NULL,
    escuela_id       bigint       NOT NULL,

    CONSTRAINT materia_pkey PRIMARY KEY (id),
    CONSTRAINT uk_materia UNIQUE (escuela_id,
                                  nombre)
);

-- =========================
-- FOREIGN KEYS
-- =========================

-- ASIGNACION
ALTER TABLE asignacion
    ADD CONSTRAINT fk_asignacion_designacion
        FOREIGN KEY (designacion_id)
            REFERENCES designacion (id);

ALTER TABLE asignacion
    ADD CONSTRAINT fk_asignacion_empleado
        FOREIGN KEY (empleado_educativo_id)
            REFERENCES empleado_educativo (id);

ALTER TABLE asignacion
    ADD CONSTRAINT fk_asignacion_caracteristica
        FOREIGN KEY (caracteristica_id)
            REFERENCES caracteristica_asignacion (id);

-- HERENCIA ASIGNACION
ALTER TABLE asignacion_provisional
    ADD CONSTRAINT fk_asig_prov
        FOREIGN KEY (id)
            REFERENCES asignacion (id);

ALTER TABLE asignacion_suplente
    ADD CONSTRAINT fk_asig_supl
        FOREIGN KEY (id)
            REFERENCES asignacion (id);

ALTER TABLE asignacion_titular
    ADD CONSTRAINT fk_asig_tit
        FOREIGN KEY (id)
            REFERENCES asignacion (id);

-- ASISTENCIA
ALTER TABLE asistencia
    ADD CONSTRAINT fk_asistencia_empleado
        FOREIGN KEY (empleado_educativo_id)
            REFERENCES empleado_educativo (id);

ALTER TABLE asistencia
    ADD CONSTRAINT fk_asistencia_escuela
        FOREIGN KEY (escuela_id)
            REFERENCES escuela (id);

ALTER TABLE asistencia
    ADD CONSTRAINT fk_asistencia_licencia
        FOREIGN KEY (licencia_id)
            REFERENCES licencia (id);

-- CURSO
ALTER TABLE curso
    ADD CONSTRAINT fk_curso_escuela
        FOREIGN KEY (escuela_id)
            REFERENCES escuela (id);

-- DESIGNACION
ALTER TABLE designacion
    ADD CONSTRAINT fk_designacion_escuela
        FOREIGN KEY (escuela_id)
            REFERENCES escuela (id);

ALTER TABLE designacion_administrativa
    ADD CONSTRAINT fk_designacion_admin
        FOREIGN KEY (id)
            REFERENCES designacion (id);

ALTER TABLE designacion_curso
    ADD CONSTRAINT fk_designacion_curso
        FOREIGN KEY (id)
            REFERENCES designacion (id);

ALTER TABLE designacion_curso
    ADD CONSTRAINT fk_designacion_curso_curso
        FOREIGN KEY (curso_id)
            REFERENCES curso (id);

ALTER TABLE designacion_curso
    ADD CONSTRAINT fk_designacion_curso_materia
        FOREIGN KEY (materia_id)
            REFERENCES materia (id);

-- EMPLEADO
ALTER TABLE empleado_educativo
    ADD CONSTRAINT fk_empleado_escuela
        FOREIGN KEY (escuela_id)
            REFERENCES escuela (id);

-- FRANJA HORARIA
ALTER TABLE franja_horaria
    ADD CONSTRAINT fk_franja_designacion
        FOREIGN KEY (designacion_id)
            REFERENCES designacion (id);

-- LICENCIA
ALTER TABLE licencia
    ADD CONSTRAINT fk_licencia_empleado
        FOREIGN KEY (empleado_id)
            REFERENCES empleado_educativo (id);

ALTER TABLE licencia
    ADD CONSTRAINT fk_licencia_anterior
        FOREIGN KEY (licencia_anterior_id)
            REFERENCES licencia (id);

-- LICENCIA DESIGNACION
ALTER TABLE licencia_designacion
    ADD CONSTRAINT fk_licencia_designacion_licencia
        FOREIGN KEY (licencia_id)
            REFERENCES licencia (id);

ALTER TABLE licencia_designacion
    ADD CONSTRAINT fk_licencia_designacion_designacion
        FOREIGN KEY (designacion_id)
            REFERENCES designacion (id);

-- MATERIA
ALTER TABLE materia
    ADD CONSTRAINT fk_materia_escuela
        FOREIGN KEY (escuela_id)
            REFERENCES escuela (id);
