export { default as FieldInputDescripcion } from "../../../shared/components/Form/FormInputDescripcion";
export * from "./DesignacionPageCreate";
export { default as DesignacionAsignacionActiva } from "./DesignacionPageDetalle/DesignacionAsignacionActiva";
export { default as DesignacionCargosHistorial } from "./DesignacionPageDetalle/DesignacionCargosHistorial";
export { default as DesignacionDatos } from "./DesignacionPageDetalle/DesignacionDatos";
export { default as DesignacionDetalleActions } from "./DesignacionPageDetalle/DesignacionDetalleActions";
export { default as DesignacionDetalleModals } from "./DesignacionPageDetalle/DesignacionDetalleModals";
export { default as DesignacionHeaderInfo } from "./DesignacionPageDetalle/DesignacionHeaderInfo";
export { default as DesignacionHorarios } from "./DesignacionPageDetalle/DesignacionHorarios";
export { default as FieldInputCupoAdministrativa } from "./FieldInputCupoAdministrativa";
export { default as FieldInputCupoCurso } from "./FieldInputCupoCurso";
export { default as FieldSelectOrientacion } from "./FieldSelectOrientacion";
export { default as FieldSelectRolEducativo } from "./FieldSelectRolEducativo";
export { default as FormSelectCurso } from "./SelectCurso";
export { default as FieldSelectMateria } from "./SelectMateria";
