export { default as AsignacionesTable } from "./AsignacionesTable";
export { default as LicenciaDesignacionHeader } from "./LicenciaDesignacionHeader";
export { default as LicenciaDesignacionItem } from "./LicenciaDesignacionItem";
export { default as LicenciaFormCreate } from "./LicenciaFormCreate";
export { default as LicenciaModalCambiarCobertura } from "./LicenciaModalCambiarCobertura";
export { default as LicenciaModalCubrirDesignaciones } from "./LicenciaModalCubrirDesignaciones";
export { default as LicenciaModalRenovarModal } from "./LicenciaModalRenovarModal";
export { default as LicenciaTable } from "./LicenciaTable";
export { default as SelectTipoLicencia } from "./SelectTipoLicencia";
