export enum SituacionDeRevista {
	TITULAR = "TITULAR",
	PROVISIONAL = "PROVISIONAL",
	SUPLENTE = "SUPLENTE",
}

export enum CaracteristicaAsignacion {
	NORMAL = "NORMAL",
	CAMBIO_DE_FUNCION = "CAMBIO_DE_FUNCION",
	RECALIFICACION_LABORAL_DEFINITIVA = "RECALIFICACION_LABORAL_DEFINITIVA",
}

export enum EstadoAsignacion {
	ACTIVA = "ACTIVA",
	LICENCIA = "LICENCIA",
	FINALIZADA = "FINALIZADA",
	BAJA = "BAJA",
	PENDIENTE = "PENDIENTE",
}

export enum CausaBaja {
	RENUNCIA = "RENUNCIA",
	CESE_DE_FUNCIONES = "CESE_DE_FUNCIONES",
	JUBILACION = "JUBILACION",
	FALLECIMIENTO = "FALLECIMIENTO",
	PASE_A_PROVISIONAL = "PASE_A_PROVISIONAL",
	OTRA = "OTRA",
}
