export enum RolEducativo {
	AUXILIAR = "AUXILIAR",
	BIBLIOTECARIO = "BIBLIOTECARIO",
	CAMBIO_DE_FUNCION = "CAMBIO_DE_FUNCION",
	DIRECCION = "DIRECCION",
	ENCARGO_DE_MEDIO_DE_APOYO_TECNICO_PROFESIONAL = "ENCARGO_DE_MEDIO_DE_APOYO_TECNICO_PROFESIONAL",
	VICEDIRECCION = "VICEDIRECCION",
	SECRETARIA = "SECRETARIA",
	ORIENTACION_EDUCACIONAL = "ORIENTACION_EDUCACIONAL",
	ORIENTACION_SOCIAL = "ORIENTACION_SOCIAL",
	PRECEPTORIA = "PRECEPTORIA",
	DOCENTE = "DOCENTE",
	RECALIFICACION_LABORAL_DEFINITIVA = "RECALIFICACION_LABORAL_DEFINITIVA",
}

export enum EstadoDesignacion {
	CUBIERTA = "CUBIERTA",
	VACANTE = "VACANTE",
}
