export enum SituacionDeRevista {
  TITULAR = "Titular",
  PROVISIONAL = "Provisional",
  SUPLENTE = "Suplente",
}

export enum CaracteristicaAsignacion {
  NORMAL = "NORMAL",
  CAMBIO_DE_FUNCION = "CAMBIO_DE_FUNCION",
  RECALIFICACION_LABORAL_DEFINITIVA = "RECALIFICACION_LABORAL_DEFINITIVA",
}

export enum RolEducativo {
  DIRECCION = "DIRECCION",
  VICEDIRECCION = "VICEDIRECCION",
  SECRETARIA = "SECRETARIA",
  ORIENTACION_EDUCACIONAL = "ORIENTACION_EDUCACIONAL",
  ORIENTACION_SOCIAL = "ORIENTACION_SOCIAL",
  BIBLIOTECARIO = "BIBLIOTECARIO",
  PRECEPTORIA = "PRECEPTORIA",
  DOCENTE = "DOCENTE",
  AUXILIAR = "AUXILIAR",
  ENCARGO_DE_MEDIO_DE_APOYO_TECNICO_PROFESIONAL = "ENCARGO_DE_MEDIO_DE_APOYO_TECNICO_PROFESIONAL",
}

export enum EstadoDesignacion {
  CUBIERTA = "CUBIERTA",
  LICENCIA = "LICENCIA",
  VACANTE = "VACANTE",
}

export enum EstadoAsignacion {
  ACTIVA = "ACTIVA",
  LICENCIA = "LICENCIA",
  FINALIZADA = "FINALIZADA",
  BAJA = "BAJA",
  PENDIENTE = "PENDIENTE",
}

export enum EstadoLicencia {
  CUBIERTA = "CUBIERTA",
  DESCUBIERTA = "DESCUBIERTA",
  INACTIVA = "INACTIVA",
}
