export enum SituacionDeRevista {
	TITULAR = "Titular",
	PROVISIONAL = "Provisional",
	SUPLENTE = "Suplente",
}

export enum CaracteristicaAsignacion {
	NORMAL = "NORMAL",
	CAMBIO_DE_FUNCION = "CAMBIO_DE_FUNCION",
	RECALIFICACION_LABORAL_DEFINITIVA = "RECALIFICACION_LABORAL_DEFINITIVA",
}

export enum RolEducativo {
	AUXILIAR = "AUXILIAR",
	BIBLIOTECARIO = "BIBLIOTECARIO",
	CAMBIO_DE_FUNCION = "CAMBIO_DE_FUNCION",
	DIRECCION = "DIRECCION",
	ENCARGO_DE_MEDIO_DE_APOYO_TECNICO_PROFESIONAL = "ENCARGO_DE_MEDIO_DE_APOYO_TECNICO_PROFESIONAL",
	VICEDIRECCION = "VICEDIRECCION",
	SECRETARIA = "SECRETARIA",
	ORIENTACION_EDUCACIONAL = "ORIENTACION_EDUCACIONAL",
	ORIENTACION_SOCIAL = "ORIENTACION_SOCIAL",
	PRECEPTORIA = "PRECEPTORIA",
	DOCENTE = "DOCENTE",
	RECALIFICACION_LABORAL_DEFINITIVA =
		"RECALIFICACION_LABORAL_DEFINITIVA",
}

export enum EstadoDesignacion {
	CUBIERTA = "CUBIERTA",
	LICENCIA = "LICENCIA",
	VACANTE = "VACANTE",
}

export enum EstadoAsignacion {
	ACTIVA = "ACTIVA",
	LICENCIA = "LICENCIA",
	FINALIZADA = "FINALIZADA",
	BAJA = "BAJA",
	PENDIENTE = "PENDIENTE",
}

export enum EstadoLicencia {
	PENDIENTE = "PENDIENTE",
	CUBIERTA = "CUBIERTA",
	DESCUBIERTA = "DESCUBIERTA",
	NO_VIGENTE = "NO_VIGENTE",
}

export enum Dia {
	LUNES = "Lunes",
	MARTES = "Martes",
	MIERCOLES = "Miércoles",
	JUEVES = "Jueves",
	VIERNES = "Viernes",
}
